/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAlagoasRouteImport } from './routes/_authenticated/alagoas'
import { Route as AuthenticatedCalculadoraAlRouteImport } from './routes/_authenticated/calculadora-al'
import { Route as AuthenticatedContratoRouteImport } from './routes/_authenticated/contrato'
import { Route as AuthenticatedPesquisasRouteImport } from './routes/_authenticated/pesquisas'
import { Route as AuthenticatedQrcodesRouteImport } from './routes/_authenticated/qrcodes'
import { Route as AuthenticatedRadarRouteImport } from './routes/_authenticated/radar'
import { Route as AuthenticatedRhRouteImport } from './routes/_authenticated/rh'
import { Route as AuthenticatedServidoresSemAcessoRouteImport } from './routes/_authenticated/servidores-sem-acesso'
import { Route as AuthenticatedSimulacaoAlagoasRouteImport } from './routes/_authenticated/simulacao-alagoas'
import { Route as AuthenticatedTomadoresAlRouteImport } from './routes/_authenticated/tomadores-al'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as AprovacaoTokenRouteImport } from './routes/aprovacao.$token'
import { Route as ConsultoraTokenRouteImport } from './routes/consultora.$token'
import { Route as AuthenticatedPosVendaAvaliacoesRouteImport } from './routes/_authenticated/pos-venda.avaliacoes'
import { Route as AuthenticatedProducaoCompeticaoRouteImport } from './routes/_authenticated/producao.competicao'
import { Route as AuthenticatedProducaoMetasRouteImport } from './routes/_authenticated/producao.metas'
import { Route as AuthenticatedProducaoMeuDiaRouteImport } from './routes/_authenticated/producao.meu-dia'
import { Route as AuthenticatedProducaoRankingRouteImport } from './routes/_authenticated/producao.ranking'
import { Route as AuthenticatedProspeccaoIndexRouteImport } from './routes/_authenticated/prospeccao.index'
import { Route as AuthenticatedProspeccaoLeadIdRouteImport } from './routes/_authenticated/prospeccao.$leadId'
import { Route as AuthenticatedProspeccaoAdminRouteImport } from './routes/_authenticated/prospeccao.admin'
import { Route as AuthenticatedProspeccaoFollowupsRouteImport } from './routes/_authenticated/prospeccao.followups'
import { Route as AuthenticatedProspeccaoPromovidosRouteImport } from './routes/_authenticated/prospeccao.promovidos'
import { Route as AuthenticatedProspeccaoPromovidosRecentementeRouteImport } from './routes/_authenticated/prospeccao.promovidos-recentemente'
import { Route as AuthenticatedProspeccaoPromovidosRecentesRouteImport } from './routes/_authenticated/prospeccao.promovidos-recentes'
import { Route as AuthenticatedProspeccaoQualidadeRouteImport } from './routes/_authenticated/prospeccao.qualidade'
import { Route as AuthenticatedProspeccaoRecentesRouteImport } from './routes/_authenticated/prospeccao.recentes'
import { Route as AuthenticatedRadarIndexRouteImport } from './routes/_authenticated/radar.index'
import { Route as AuthenticatedRadarArquivosRouteImport } from './routes/_authenticated/radar.arquivos'
import { Route as AuthenticatedRadarBuscaDiariaRouteImport } from './routes/_authenticated/radar.busca-diaria'
import { Route as AuthenticatedRadarImportarRouteImport } from './routes/_authenticated/radar.importar'
import { Route as AuthenticatedRadarRegistrosRouteImport } from './routes/_authenticated/radar.registros'
import { Route as AuthenticatedRhIndexRouteImport } from './routes/_authenticated/rh.index'
import { Route as AuthenticatedRhAcessosRouteImport } from './routes/_authenticated/rh.acessos'
import { Route as AuthenticatedRhAvaliacoesRouteImport } from './routes/_authenticated/rh.avaliacoes'
import { Route as AuthenticatedRhBancoHorasRouteImport } from './routes/_authenticated/rh.banco-horas'
import { Route as AuthenticatedRhCargosRouteImport } from './routes/_authenticated/rh.cargos'
import { Route as AuthenticatedRhClimaRouteImport } from './routes/_authenticated/rh.clima'
import { Route as AuthenticatedRhColaboradoresRouteImport } from './routes/_authenticated/rh.colaboradores'
import { Route as AuthenticatedRhDashboardRouteImport } from './routes/_authenticated/rh.dashboard'
import { Route as AuthenticatedRhDepartamentosRouteImport } from './routes/_authenticated/rh.departamentos'
import { Route as AuthenticatedRhDesligamentosRouteImport } from './routes/_authenticated/rh.desligamentos'
import { Route as AuthenticatedRhDocumentosRouteImport } from './routes/_authenticated/rh.documentos'
import { Route as AuthenticatedRhEquipamentosRouteImport } from './routes/_authenticated/rh.equipamentos'
import { Route as AuthenticatedRhFeriasRouteImport } from './routes/_authenticated/rh.ferias'
import { Route as AuthenticatedRhHoleritesRouteImport } from './routes/_authenticated/rh.holerites'
import { Route as AuthenticatedRhOcorrenciasRouteImport } from './routes/_authenticated/rh.ocorrencias'
import { Route as AuthenticatedRhOkrsRouteImport } from './routes/_authenticated/rh.okrs'
import { Route as AuthenticatedRhOnboardingRouteImport } from './routes/_authenticated/rh.onboarding'
import { Route as AuthenticatedRhOrganogramaRouteImport } from './routes/_authenticated/rh.organograma'
import { Route as AuthenticatedRhPdiRouteImport } from './routes/_authenticated/rh.pdi'
import { Route as AuthenticatedRhPortalRouteImport } from './routes/_authenticated/rh.portal'
import { Route as AuthenticatedRhProducaoRouteImport } from './routes/_authenticated/rh.producao'
import { Route as AuthenticatedRhReconhecimentosRouteImport } from './routes/_authenticated/rh.reconhecimentos'
import { Route as AuthenticatedRhRecrutamentoRouteImport } from './routes/_authenticated/rh.recrutamento'
import { Route as AuthenticatedRhTreinamentosRouteImport } from './routes/_authenticated/rh.treinamentos'
import { Route as AuthenticatedRhTurnoverRouteImport } from './routes/_authenticated/rh.turnover'
import { Route as AuthenticatedProspeccaoAdminLeadsRouteImport } from './routes/_authenticated/prospeccao.admin.leads'
import { Route as AuthenticatedRhColaboradoresIdRouteImport } from './routes/_authenticated/rh.colaboradores.$id'
import { Route as AuthenticatedRhPortalIndexRouteImport } from './routes/_authenticated/rh.portal.index'
import { Route as AuthenticatedRhPortalKpiRouteImport } from './routes/_authenticated/rh.portal.$kpi'
import { Route as ApiPublicHooksCompeticaoFecharRouteImport } from './routes/api/public/hooks/competicao-fechar'
import { Route as ApiPublicHooksFollowupLembretesRouteImport } from './routes/api/public/hooks/followup-lembretes'
import { Route as ApiPublicHooksRadarDiarioRouteImport } from './routes/api/public/hooks/radar-diario'
import { Route as ApiPublicHooksRadarDiarioWorkerRouteImport } from './routes/api/public/hooks/radar-diario-worker'
import { Route as ApiPublicHooksRadarDistribuirRouteImport } from './routes/api/public/hooks/radar-distribuir'
import { Route as ApiPublicHooksRadarSemanalRouteImport } from './routes/api/public/hooks/radar-semanal'
import { Route as ApiPublicHooksTomadoresReporRouteImport } from './routes/api/public/hooks/tomadores-repor'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAlagoasRoute = AuthenticatedAlagoasRouteImport.update({
  id: '/alagoas',
  path: '/alagoas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalculadoraAlRoute =
  AuthenticatedCalculadoraAlRouteImport.update({
    id: '/calculadora-al',
    path: '/calculadora-al',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContratoRoute = AuthenticatedContratoRouteImport.update({
  id: '/contrato',
  path: '/contrato',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPesquisasRoute = AuthenticatedPesquisasRouteImport.update({
  id: '/pesquisas',
  path: '/pesquisas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQrcodesRoute = AuthenticatedQrcodesRouteImport.update({
  id: '/qrcodes',
  path: '/qrcodes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRadarRoute = AuthenticatedRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRhRoute = AuthenticatedRhRouteImport.update({
  id: '/rh',
  path: '/rh',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServidoresSemAcessoRoute =
  AuthenticatedServidoresSemAcessoRouteImport.update({
    id: '/servidores-sem-acesso',
    path: '/servidores-sem-acesso',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSimulacaoAlagoasRoute =
  AuthenticatedSimulacaoAlagoasRouteImport.update({
    id: '/simulacao-alagoas',
    path: '/simulacao-alagoas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTomadoresAlRoute =
  AuthenticatedTomadoresAlRouteImport.update({
    id: '/tomadores-al',
    path: '/tomadores-al',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AprovacaoTokenRoute = AprovacaoTokenRouteImport.update({
  id: '/aprovacao/$token',
  path: '/aprovacao/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultoraTokenRoute = ConsultoraTokenRouteImport.update({
  id: '/consultora/$token',
  path: '/consultora/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPosVendaAvaliacoesRoute =
  AuthenticatedPosVendaAvaliacoesRouteImport.update({
    id: '/pos-venda/avaliacoes',
    path: '/pos-venda/avaliacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProducaoCompeticaoRoute =
  AuthenticatedProducaoCompeticaoRouteImport.update({
    id: '/producao/competicao',
    path: '/producao/competicao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProducaoMetasRoute =
  AuthenticatedProducaoMetasRouteImport.update({
    id: '/producao/metas',
    path: '/producao/metas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProducaoMeuDiaRoute =
  AuthenticatedProducaoMeuDiaRouteImport.update({
    id: '/producao/meu-dia',
    path: '/producao/meu-dia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProducaoRankingRoute =
  AuthenticatedProducaoRankingRouteImport.update({
    id: '/producao/ranking',
    path: '/producao/ranking',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProspeccaoIndexRoute =
  AuthenticatedProspeccaoIndexRouteImport.update({
    id: '/prospeccao/',
    path: '/prospeccao/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProspeccaoLeadIdRoute =
  AuthenticatedProspeccaoLeadIdRouteImport.update({
    id: '/prospeccao/$leadId',
    path: '/prospeccao/$leadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProspeccaoAdminRoute =
  AuthenticatedProspeccaoAdminRouteImport.update({
    id: '/prospeccao/admin',
    path: '/prospeccao/admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProspeccaoFollowupsRoute =
  AuthenticatedProspeccaoFollowupsRouteImport.update({
    id: '/prospeccao/followups',
    path: '/prospeccao/followups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProspeccaoPromovidosRoute =
  AuthenticatedProspeccaoPromovidosRouteImport.update({
    id: '/prospeccao/promovidos',
    path: '/prospeccao/promovidos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProspeccaoPromovidosRecentementeRoute =
  AuthenticatedProspeccaoPromovidosRecentementeRouteImport.update({
    id: '/prospeccao/promovidos-recentemente',
    path: '/prospeccao/promovidos-recentemente',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProspeccaoPromovidosRecentesRoute =
  AuthenticatedProspeccaoPromovidosRecentesRouteImport.update({
    id: '/prospeccao/promovidos-recentes',
    path: '/prospeccao/promovidos-recentes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProspeccaoQualidadeRoute =
  AuthenticatedProspeccaoQualidadeRouteImport.update({
    id: '/prospeccao/qualidade',
    path: '/prospeccao/qualidade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProspeccaoRecentesRoute =
  AuthenticatedProspeccaoRecentesRouteImport.update({
    id: '/prospeccao/recentes',
    path: '/prospeccao/recentes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRadarIndexRoute = AuthenticatedRadarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRadarRoute,
} as any)
const AuthenticatedRadarArquivosRoute =
  AuthenticatedRadarArquivosRouteImport.update({
    id: '/arquivos',
    path: '/arquivos',
    getParentRoute: () => AuthenticatedRadarRoute,
  } as any)
const AuthenticatedRadarBuscaDiariaRoute =
  AuthenticatedRadarBuscaDiariaRouteImport.update({
    id: '/busca-diaria',
    path: '/busca-diaria',
    getParentRoute: () => AuthenticatedRadarRoute,
  } as any)
const AuthenticatedRadarImportarRoute =
  AuthenticatedRadarImportarRouteImport.update({
    id: '/importar',
    path: '/importar',
    getParentRoute: () => AuthenticatedRadarRoute,
  } as any)
const AuthenticatedRadarRegistrosRoute =
  AuthenticatedRadarRegistrosRouteImport.update({
    id: '/registros',
    path: '/registros',
    getParentRoute: () => AuthenticatedRadarRoute,
  } as any)
const AuthenticatedRhIndexRoute = AuthenticatedRhIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRhRoute,
} as any)
const AuthenticatedRhAcessosRoute = AuthenticatedRhAcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => AuthenticatedRhRoute,
} as any)
const AuthenticatedRhAvaliacoesRoute =
  AuthenticatedRhAvaliacoesRouteImport.update({
    id: '/avaliacoes',
    path: '/avaliacoes',
    getParentRoute: () => AuthenticatedRhRoute,
  } as any)
const AuthenticatedRhBancoHorasRoute =
  AuthenticatedRhBancoHorasRouteImport.update({
    id: '/banco-horas',
    path: '/banco-horas',
    getParentRoute: () => AuthenticatedRhRoute,
  } as any)
const AuthenticatedRhCargosRoute = AuthenticatedRhCargosRouteImport.update({
  id: '/cargos',
  path: '/cargos',
  getParentRoute: () => AuthenticatedRhRoute,
} as any)
const AuthenticatedRhClimaRoute = AuthenticatedRhClimaRouteImport.update({
  id: '/clima',
  path: '/clima',
  getParentRoute: () => AuthenticatedRhRoute,
} as any)
const AuthenticatedRhColaboradoresRoute =
  AuthenticatedRhColaboradoresRouteImport.update({
    id: '/colaboradores',
    path: '/colaboradores',
    getParentRoute: () => AuthenticatedRhRoute,
  } as any)
const AuthenticatedRhDashboardRoute =
  AuthenticatedRhDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRhRoute,
  } as any)
const AuthenticatedRhDepartamentosRoute =
  AuthenticatedRhDepartamentosRouteImport.update({
    id: '/departamentos',
    path: '/departamentos',
    getParentRoute: () => AuthenticatedRhRoute,
  } as any)
const AuthenticatedRhDesligamentosRoute =
  AuthenticatedRhDesligamentosRouteImport.update({
    id: '/desligamentos',
    path: '/desligamentos',
    getParentRoute: () => AuthenticatedRhRoute,
  } as any)
const AuthenticatedRhDocumentosRoute =
  AuthenticatedRhDocumentosRouteImport.update({
    id: '/documentos',
    path: '/documentos',
    getParentRoute: () => AuthenticatedRhRoute,
  } as any)
const AuthenticatedRhEquipamentosRoute =
  AuthenticatedRhEquipamentosRouteImport.update({
    id: '/equipamentos',
    path: '/equipamentos',
    getParentRoute: () => AuthenticatedRhRoute,
  } as any)
const AuthenticatedRhFeriasRoute = AuthenticatedRhFeriasRouteImport.update({
  id: '/ferias',
  path: '/ferias',
  getParentRoute: () => AuthenticatedRhRoute,
} as any)
const AuthenticatedRhHoleritesRoute =
  AuthenticatedRhHoleritesRouteImport.update({
    id: '/holerites',
    path: '/holerites',
    getParentRoute: () => AuthenticatedRhRoute,
  } as any)
const AuthenticatedRhOcorrenciasRoute =
  AuthenticatedRhOcorrenciasRouteImport.update({
    id: '/ocorrencias',
    path: '/ocorrencias',
    getParentRoute: () => AuthenticatedRhRoute,
  } as any)
const AuthenticatedRhOkrsRoute = AuthenticatedRhOkrsRouteImport.update({
  id: '/okrs',
  path: '/okrs',
  getParentRoute: () => AuthenticatedRhRoute,
} as any)
const AuthenticatedRhOnboardingRoute =
  AuthenticatedRhOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedRhRoute,
  } as any)
const AuthenticatedRhOrganogramaRoute =
  AuthenticatedRhOrganogramaRouteImport.update({
    id: '/organograma',
    path: '/organograma',
    getParentRoute: () => AuthenticatedRhRoute,
  } as any)
const AuthenticatedRhPdiRoute = AuthenticatedRhPdiRouteImport.update({
  id: '/pdi',
  path: '/pdi',
  getParentRoute: () => AuthenticatedRhRoute,
} as any)
const AuthenticatedRhPortalRoute = AuthenticatedRhPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRhRoute,
} as any)
const AuthenticatedRhProducaoRoute = AuthenticatedRhProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => AuthenticatedRhRoute,
} as any)
const AuthenticatedRhReconhecimentosRoute =
  AuthenticatedRhReconhecimentosRouteImport.update({
    id: '/reconhecimentos',
    path: '/reconhecimentos',
    getParentRoute: () => AuthenticatedRhRoute,
  } as any)
const AuthenticatedRhRecrutamentoRoute =
  AuthenticatedRhRecrutamentoRouteImport.update({
    id: '/recrutamento',
    path: '/recrutamento',
    getParentRoute: () => AuthenticatedRhRoute,
  } as any)
const AuthenticatedRhTreinamentosRoute =
  AuthenticatedRhTreinamentosRouteImport.update({
    id: '/treinamentos',
    path: '/treinamentos',
    getParentRoute: () => AuthenticatedRhRoute,
  } as any)
const AuthenticatedRhTurnoverRoute = AuthenticatedRhTurnoverRouteImport.update({
  id: '/turnover',
  path: '/turnover',
  getParentRoute: () => AuthenticatedRhRoute,
} as any)
const AuthenticatedProspeccaoAdminLeadsRoute =
  AuthenticatedProspeccaoAdminLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedProspeccaoAdminRoute,
  } as any)
const AuthenticatedRhColaboradoresIdRoute =
  AuthenticatedRhColaboradoresIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedRhColaboradoresRoute,
  } as any)
const AuthenticatedRhPortalIndexRoute =
  AuthenticatedRhPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedRhPortalRoute,
  } as any)
const AuthenticatedRhPortalKpiRoute =
  AuthenticatedRhPortalKpiRouteImport.update({
    id: '/$kpi',
    path: '/$kpi',
    getParentRoute: () => AuthenticatedRhPortalRoute,
  } as any)
const ApiPublicHooksCompeticaoFecharRoute =
  ApiPublicHooksCompeticaoFecharRouteImport.update({
    id: '/api/public/hooks/competicao-fechar',
    path: '/api/public/hooks/competicao-fechar',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksFollowupLembretesRoute =
  ApiPublicHooksFollowupLembretesRouteImport.update({
    id: '/api/public/hooks/followup-lembretes',
    path: '/api/public/hooks/followup-lembretes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRadarDiarioRoute =
  ApiPublicHooksRadarDiarioRouteImport.update({
    id: '/api/public/hooks/radar-diario',
    path: '/api/public/hooks/radar-diario',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRadarDiarioWorkerRoute =
  ApiPublicHooksRadarDiarioWorkerRouteImport.update({
    id: '/api/public/hooks/radar-diario-worker',
    path: '/api/public/hooks/radar-diario-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRadarDistribuirRoute =
  ApiPublicHooksRadarDistribuirRouteImport.update({
    id: '/api/public/hooks/radar-distribuir',
    path: '/api/public/hooks/radar-distribuir',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRadarSemanalRoute =
  ApiPublicHooksRadarSemanalRouteImport.update({
    id: '/api/public/hooks/radar-semanal',
    path: '/api/public/hooks/radar-semanal',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTomadoresReporRoute =
  ApiPublicHooksTomadoresReporRouteImport.update({
    id: '/api/public/hooks/tomadores-repor',
    path: '/api/public/hooks/tomadores-repor',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/alagoas': typeof AuthenticatedAlagoasRoute
  '/calculadora-al': typeof AuthenticatedCalculadoraAlRoute
  '/contrato': typeof AuthenticatedContratoRoute
  '/pesquisas': typeof AuthenticatedPesquisasRoute
  '/qrcodes': typeof AuthenticatedQrcodesRoute
  '/radar': typeof AuthenticatedRadarRouteWithChildren
  '/rh': typeof AuthenticatedRhRouteWithChildren
  '/servidores-sem-acesso': typeof AuthenticatedServidoresSemAcessoRoute
  '/simulacao-alagoas': typeof AuthenticatedSimulacaoAlagoasRoute
  '/tomadores-al': typeof AuthenticatedTomadoresAlRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/aprovacao/$token': typeof AprovacaoTokenRoute
  '/consultora/$token': typeof ConsultoraTokenRoute
  '/pos-venda/avaliacoes': typeof AuthenticatedPosVendaAvaliacoesRoute
  '/producao/competicao': typeof AuthenticatedProducaoCompeticaoRoute
  '/producao/metas': typeof AuthenticatedProducaoMetasRoute
  '/producao/meu-dia': typeof AuthenticatedProducaoMeuDiaRoute
  '/producao/ranking': typeof AuthenticatedProducaoRankingRoute
  '/prospeccao/$leadId': typeof AuthenticatedProspeccaoLeadIdRoute
  '/prospeccao/admin': typeof AuthenticatedProspeccaoAdminRouteWithChildren
  '/prospeccao/followups': typeof AuthenticatedProspeccaoFollowupsRoute
  '/prospeccao/promovidos': typeof AuthenticatedProspeccaoPromovidosRoute
  '/prospeccao/promovidos-recentemente': typeof AuthenticatedProspeccaoPromovidosRecentementeRoute
  '/prospeccao/promovidos-recentes': typeof AuthenticatedProspeccaoPromovidosRecentesRoute
  '/prospeccao/qualidade': typeof AuthenticatedProspeccaoQualidadeRoute
  '/prospeccao/recentes': typeof AuthenticatedProspeccaoRecentesRoute
  '/radar/arquivos': typeof AuthenticatedRadarArquivosRoute
  '/radar/busca-diaria': typeof AuthenticatedRadarBuscaDiariaRoute
  '/radar/importar': typeof AuthenticatedRadarImportarRoute
  '/radar/registros': typeof AuthenticatedRadarRegistrosRoute
  '/rh/acessos': typeof AuthenticatedRhAcessosRoute
  '/rh/avaliacoes': typeof AuthenticatedRhAvaliacoesRoute
  '/rh/banco-horas': typeof AuthenticatedRhBancoHorasRoute
  '/rh/cargos': typeof AuthenticatedRhCargosRoute
  '/rh/clima': typeof AuthenticatedRhClimaRoute
  '/rh/colaboradores': typeof AuthenticatedRhColaboradoresRouteWithChildren
  '/rh/dashboard': typeof AuthenticatedRhDashboardRoute
  '/rh/departamentos': typeof AuthenticatedRhDepartamentosRoute
  '/rh/desligamentos': typeof AuthenticatedRhDesligamentosRoute
  '/rh/documentos': typeof AuthenticatedRhDocumentosRoute
  '/rh/equipamentos': typeof AuthenticatedRhEquipamentosRoute
  '/rh/ferias': typeof AuthenticatedRhFeriasRoute
  '/rh/holerites': typeof AuthenticatedRhHoleritesRoute
  '/rh/ocorrencias': typeof AuthenticatedRhOcorrenciasRoute
  '/rh/okrs': typeof AuthenticatedRhOkrsRoute
  '/rh/onboarding': typeof AuthenticatedRhOnboardingRoute
  '/rh/organograma': typeof AuthenticatedRhOrganogramaRoute
  '/rh/pdi': typeof AuthenticatedRhPdiRoute
  '/rh/portal': typeof AuthenticatedRhPortalRouteWithChildren
  '/rh/producao': typeof AuthenticatedRhProducaoRoute
  '/rh/reconhecimentos': typeof AuthenticatedRhReconhecimentosRoute
  '/rh/recrutamento': typeof AuthenticatedRhRecrutamentoRoute
  '/rh/treinamentos': typeof AuthenticatedRhTreinamentosRoute
  '/rh/turnover': typeof AuthenticatedRhTurnoverRoute
  '/prospeccao/': typeof AuthenticatedProspeccaoIndexRoute
  '/radar/': typeof AuthenticatedRadarIndexRoute
  '/rh/': typeof AuthenticatedRhIndexRoute
  '/prospeccao/admin/leads': typeof AuthenticatedProspeccaoAdminLeadsRoute
  '/rh/colaboradores/$id': typeof AuthenticatedRhColaboradoresIdRoute
  '/rh/portal/$kpi': typeof AuthenticatedRhPortalKpiRoute
  '/api/public/hooks/competicao-fechar': typeof ApiPublicHooksCompeticaoFecharRoute
  '/api/public/hooks/followup-lembretes': typeof ApiPublicHooksFollowupLembretesRoute
  '/api/public/hooks/radar-diario': typeof ApiPublicHooksRadarDiarioRoute
  '/api/public/hooks/radar-diario-worker': typeof ApiPublicHooksRadarDiarioWorkerRoute
  '/api/public/hooks/radar-distribuir': typeof ApiPublicHooksRadarDistribuirRoute
  '/api/public/hooks/radar-semanal': typeof ApiPublicHooksRadarSemanalRoute
  '/api/public/hooks/tomadores-repor': typeof ApiPublicHooksTomadoresReporRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/rh/portal/': typeof AuthenticatedRhPortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/alagoas': typeof AuthenticatedAlagoasRoute
  '/calculadora-al': typeof AuthenticatedCalculadoraAlRoute
  '/contrato': typeof AuthenticatedContratoRoute
  '/pesquisas': typeof AuthenticatedPesquisasRoute
  '/qrcodes': typeof AuthenticatedQrcodesRoute
  '/servidores-sem-acesso': typeof AuthenticatedServidoresSemAcessoRoute
  '/simulacao-alagoas': typeof AuthenticatedSimulacaoAlagoasRoute
  '/tomadores-al': typeof AuthenticatedTomadoresAlRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/aprovacao/$token': typeof AprovacaoTokenRoute
  '/consultora/$token': typeof ConsultoraTokenRoute
  '/pos-venda/avaliacoes': typeof AuthenticatedPosVendaAvaliacoesRoute
  '/producao/competicao': typeof AuthenticatedProducaoCompeticaoRoute
  '/producao/metas': typeof AuthenticatedProducaoMetasRoute
  '/producao/meu-dia': typeof AuthenticatedProducaoMeuDiaRoute
  '/producao/ranking': typeof AuthenticatedProducaoRankingRoute
  '/prospeccao/$leadId': typeof AuthenticatedProspeccaoLeadIdRoute
  '/prospeccao/admin': typeof AuthenticatedProspeccaoAdminRouteWithChildren
  '/prospeccao/followups': typeof AuthenticatedProspeccaoFollowupsRoute
  '/prospeccao/promovidos': typeof AuthenticatedProspeccaoPromovidosRoute
  '/prospeccao/promovidos-recentemente': typeof AuthenticatedProspeccaoPromovidosRecentementeRoute
  '/prospeccao/promovidos-recentes': typeof AuthenticatedProspeccaoPromovidosRecentesRoute
  '/prospeccao/qualidade': typeof AuthenticatedProspeccaoQualidadeRoute
  '/prospeccao/recentes': typeof AuthenticatedProspeccaoRecentesRoute
  '/radar/arquivos': typeof AuthenticatedRadarArquivosRoute
  '/radar/busca-diaria': typeof AuthenticatedRadarBuscaDiariaRoute
  '/radar/importar': typeof AuthenticatedRadarImportarRoute
  '/radar/registros': typeof AuthenticatedRadarRegistrosRoute
  '/rh/acessos': typeof AuthenticatedRhAcessosRoute
  '/rh/avaliacoes': typeof AuthenticatedRhAvaliacoesRoute
  '/rh/banco-horas': typeof AuthenticatedRhBancoHorasRoute
  '/rh/cargos': typeof AuthenticatedRhCargosRoute
  '/rh/clima': typeof AuthenticatedRhClimaRoute
  '/rh/colaboradores': typeof AuthenticatedRhColaboradoresRouteWithChildren
  '/rh/dashboard': typeof AuthenticatedRhDashboardRoute
  '/rh/departamentos': typeof AuthenticatedRhDepartamentosRoute
  '/rh/desligamentos': typeof AuthenticatedRhDesligamentosRoute
  '/rh/documentos': typeof AuthenticatedRhDocumentosRoute
  '/rh/equipamentos': typeof AuthenticatedRhEquipamentosRoute
  '/rh/ferias': typeof AuthenticatedRhFeriasRoute
  '/rh/holerites': typeof AuthenticatedRhHoleritesRoute
  '/rh/ocorrencias': typeof AuthenticatedRhOcorrenciasRoute
  '/rh/okrs': typeof AuthenticatedRhOkrsRoute
  '/rh/onboarding': typeof AuthenticatedRhOnboardingRoute
  '/rh/organograma': typeof AuthenticatedRhOrganogramaRoute
  '/rh/pdi': typeof AuthenticatedRhPdiRoute
  '/rh/producao': typeof AuthenticatedRhProducaoRoute
  '/rh/reconhecimentos': typeof AuthenticatedRhReconhecimentosRoute
  '/rh/recrutamento': typeof AuthenticatedRhRecrutamentoRoute
  '/rh/treinamentos': typeof AuthenticatedRhTreinamentosRoute
  '/rh/turnover': typeof AuthenticatedRhTurnoverRoute
  '/prospeccao': typeof AuthenticatedProspeccaoIndexRoute
  '/radar': typeof AuthenticatedRadarIndexRoute
  '/rh': typeof AuthenticatedRhIndexRoute
  '/prospeccao/admin/leads': typeof AuthenticatedProspeccaoAdminLeadsRoute
  '/rh/colaboradores/$id': typeof AuthenticatedRhColaboradoresIdRoute
  '/rh/portal/$kpi': typeof AuthenticatedRhPortalKpiRoute
  '/api/public/hooks/competicao-fechar': typeof ApiPublicHooksCompeticaoFecharRoute
  '/api/public/hooks/followup-lembretes': typeof ApiPublicHooksFollowupLembretesRoute
  '/api/public/hooks/radar-diario': typeof ApiPublicHooksRadarDiarioRoute
  '/api/public/hooks/radar-diario-worker': typeof ApiPublicHooksRadarDiarioWorkerRoute
  '/api/public/hooks/radar-distribuir': typeof ApiPublicHooksRadarDistribuirRoute
  '/api/public/hooks/radar-semanal': typeof ApiPublicHooksRadarSemanalRoute
  '/api/public/hooks/tomadores-repor': typeof ApiPublicHooksTomadoresReporRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/rh/portal': typeof AuthenticatedRhPortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/alagoas': typeof AuthenticatedAlagoasRoute
  '/_authenticated/calculadora-al': typeof AuthenticatedCalculadoraAlRoute
  '/_authenticated/contrato': typeof AuthenticatedContratoRoute
  '/_authenticated/pesquisas': typeof AuthenticatedPesquisasRoute
  '/_authenticated/qrcodes': typeof AuthenticatedQrcodesRoute
  '/_authenticated/radar': typeof AuthenticatedRadarRouteWithChildren
  '/_authenticated/rh': typeof AuthenticatedRhRouteWithChildren
  '/_authenticated/servidores-sem-acesso': typeof AuthenticatedServidoresSemAcessoRoute
  '/_authenticated/simulacao-alagoas': typeof AuthenticatedSimulacaoAlagoasRoute
  '/_authenticated/tomadores-al': typeof AuthenticatedTomadoresAlRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/aprovacao/$token': typeof AprovacaoTokenRoute
  '/consultora/$token': typeof ConsultoraTokenRoute
  '/_authenticated/pos-venda/avaliacoes': typeof AuthenticatedPosVendaAvaliacoesRoute
  '/_authenticated/producao/competicao': typeof AuthenticatedProducaoCompeticaoRoute
  '/_authenticated/producao/metas': typeof AuthenticatedProducaoMetasRoute
  '/_authenticated/producao/meu-dia': typeof AuthenticatedProducaoMeuDiaRoute
  '/_authenticated/producao/ranking': typeof AuthenticatedProducaoRankingRoute
  '/_authenticated/prospeccao/$leadId': typeof AuthenticatedProspeccaoLeadIdRoute
  '/_authenticated/prospeccao/admin': typeof AuthenticatedProspeccaoAdminRouteWithChildren
  '/_authenticated/prospeccao/followups': typeof AuthenticatedProspeccaoFollowupsRoute
  '/_authenticated/prospeccao/promovidos': typeof AuthenticatedProspeccaoPromovidosRoute
  '/_authenticated/prospeccao/promovidos-recentemente': typeof AuthenticatedProspeccaoPromovidosRecentementeRoute
  '/_authenticated/prospeccao/promovidos-recentes': typeof AuthenticatedProspeccaoPromovidosRecentesRoute
  '/_authenticated/prospeccao/qualidade': typeof AuthenticatedProspeccaoQualidadeRoute
  '/_authenticated/prospeccao/recentes': typeof AuthenticatedProspeccaoRecentesRoute
  '/_authenticated/radar/arquivos': typeof AuthenticatedRadarArquivosRoute
  '/_authenticated/radar/busca-diaria': typeof AuthenticatedRadarBuscaDiariaRoute
  '/_authenticated/radar/importar': typeof AuthenticatedRadarImportarRoute
  '/_authenticated/radar/registros': typeof AuthenticatedRadarRegistrosRoute
  '/_authenticated/rh/acessos': typeof AuthenticatedRhAcessosRoute
  '/_authenticated/rh/avaliacoes': typeof AuthenticatedRhAvaliacoesRoute
  '/_authenticated/rh/banco-horas': typeof AuthenticatedRhBancoHorasRoute
  '/_authenticated/rh/cargos': typeof AuthenticatedRhCargosRoute
  '/_authenticated/rh/clima': typeof AuthenticatedRhClimaRoute
  '/_authenticated/rh/colaboradores': typeof AuthenticatedRhColaboradoresRouteWithChildren
  '/_authenticated/rh/dashboard': typeof AuthenticatedRhDashboardRoute
  '/_authenticated/rh/departamentos': typeof AuthenticatedRhDepartamentosRoute
  '/_authenticated/rh/desligamentos': typeof AuthenticatedRhDesligamentosRoute
  '/_authenticated/rh/documentos': typeof AuthenticatedRhDocumentosRoute
  '/_authenticated/rh/equipamentos': typeof AuthenticatedRhEquipamentosRoute
  '/_authenticated/rh/ferias': typeof AuthenticatedRhFeriasRoute
  '/_authenticated/rh/holerites': typeof AuthenticatedRhHoleritesRoute
  '/_authenticated/rh/ocorrencias': typeof AuthenticatedRhOcorrenciasRoute
  '/_authenticated/rh/okrs': typeof AuthenticatedRhOkrsRoute
  '/_authenticated/rh/onboarding': typeof AuthenticatedRhOnboardingRoute
  '/_authenticated/rh/organograma': typeof AuthenticatedRhOrganogramaRoute
  '/_authenticated/rh/pdi': typeof AuthenticatedRhPdiRoute
  '/_authenticated/rh/portal': typeof AuthenticatedRhPortalRouteWithChildren
  '/_authenticated/rh/producao': typeof AuthenticatedRhProducaoRoute
  '/_authenticated/rh/reconhecimentos': typeof AuthenticatedRhReconhecimentosRoute
  '/_authenticated/rh/recrutamento': typeof AuthenticatedRhRecrutamentoRoute
  '/_authenticated/rh/treinamentos': typeof AuthenticatedRhTreinamentosRoute
  '/_authenticated/rh/turnover': typeof AuthenticatedRhTurnoverRoute
  '/_authenticated/prospeccao/': typeof AuthenticatedProspeccaoIndexRoute
  '/_authenticated/radar/': typeof AuthenticatedRadarIndexRoute
  '/_authenticated/rh/': typeof AuthenticatedRhIndexRoute
  '/_authenticated/prospeccao/admin/leads': typeof AuthenticatedProspeccaoAdminLeadsRoute
  '/_authenticated/rh/colaboradores/$id': typeof AuthenticatedRhColaboradoresIdRoute
  '/_authenticated/rh/portal/$kpi': typeof AuthenticatedRhPortalKpiRoute
  '/api/public/hooks/competicao-fechar': typeof ApiPublicHooksCompeticaoFecharRoute
  '/api/public/hooks/followup-lembretes': typeof ApiPublicHooksFollowupLembretesRoute
  '/api/public/hooks/radar-diario': typeof ApiPublicHooksRadarDiarioRoute
  '/api/public/hooks/radar-diario-worker': typeof ApiPublicHooksRadarDiarioWorkerRoute
  '/api/public/hooks/radar-distribuir': typeof ApiPublicHooksRadarDistribuirRoute
  '/api/public/hooks/radar-semanal': typeof ApiPublicHooksRadarSemanalRoute
  '/api/public/hooks/tomadores-repor': typeof ApiPublicHooksTomadoresReporRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/_authenticated/rh/portal/': typeof AuthenticatedRhPortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/sitemap.xml'
    | '/alagoas'
    | '/calculadora-al'
    | '/contrato'
    | '/pesquisas'
    | '/qrcodes'
    | '/radar'
    | '/rh'
    | '/servidores-sem-acesso'
    | '/simulacao-alagoas'
    | '/tomadores-al'
    | '/whatsapp'
    | '/aprovacao/$token'
    | '/consultora/$token'
    | '/pos-venda/avaliacoes'
    | '/producao/competicao'
    | '/producao/metas'
    | '/producao/meu-dia'
    | '/producao/ranking'
    | '/prospeccao/$leadId'
    | '/prospeccao/admin'
    | '/prospeccao/followups'
    | '/prospeccao/promovidos'
    | '/prospeccao/promovidos-recentemente'
    | '/prospeccao/promovidos-recentes'
    | '/prospeccao/qualidade'
    | '/prospeccao/recentes'
    | '/radar/arquivos'
    | '/radar/busca-diaria'
    | '/radar/importar'
    | '/radar/registros'
    | '/rh/acessos'
    | '/rh/avaliacoes'
    | '/rh/banco-horas'
    | '/rh/cargos'
    | '/rh/clima'
    | '/rh/colaboradores'
    | '/rh/dashboard'
    | '/rh/departamentos'
    | '/rh/desligamentos'
    | '/rh/documentos'
    | '/rh/equipamentos'
    | '/rh/ferias'
    | '/rh/holerites'
    | '/rh/ocorrencias'
    | '/rh/okrs'
    | '/rh/onboarding'
    | '/rh/organograma'
    | '/rh/pdi'
    | '/rh/portal'
    | '/rh/producao'
    | '/rh/reconhecimentos'
    | '/rh/recrutamento'
    | '/rh/treinamentos'
    | '/rh/turnover'
    | '/prospeccao/'
    | '/radar/'
    | '/rh/'
    | '/prospeccao/admin/leads'
    | '/rh/colaboradores/$id'
    | '/rh/portal/$kpi'
    | '/api/public/hooks/competicao-fechar'
    | '/api/public/hooks/followup-lembretes'
    | '/api/public/hooks/radar-diario'
    | '/api/public/hooks/radar-diario-worker'
    | '/api/public/hooks/radar-distribuir'
    | '/api/public/hooks/radar-semanal'
    | '/api/public/hooks/tomadores-repor'
    | '/api/public/whatsapp/webhook'
    | '/rh/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/sitemap.xml'
    | '/alagoas'
    | '/calculadora-al'
    | '/contrato'
    | '/pesquisas'
    | '/qrcodes'
    | '/servidores-sem-acesso'
    | '/simulacao-alagoas'
    | '/tomadores-al'
    | '/whatsapp'
    | '/aprovacao/$token'
    | '/consultora/$token'
    | '/pos-venda/avaliacoes'
    | '/producao/competicao'
    | '/producao/metas'
    | '/producao/meu-dia'
    | '/producao/ranking'
    | '/prospeccao/$leadId'
    | '/prospeccao/admin'
    | '/prospeccao/followups'
    | '/prospeccao/promovidos'
    | '/prospeccao/promovidos-recentemente'
    | '/prospeccao/promovidos-recentes'
    | '/prospeccao/qualidade'
    | '/prospeccao/recentes'
    | '/radar/arquivos'
    | '/radar/busca-diaria'
    | '/radar/importar'
    | '/radar/registros'
    | '/rh/acessos'
    | '/rh/avaliacoes'
    | '/rh/banco-horas'
    | '/rh/cargos'
    | '/rh/clima'
    | '/rh/colaboradores'
    | '/rh/dashboard'
    | '/rh/departamentos'
    | '/rh/desligamentos'
    | '/rh/documentos'
    | '/rh/equipamentos'
    | '/rh/ferias'
    | '/rh/holerites'
    | '/rh/ocorrencias'
    | '/rh/okrs'
    | '/rh/onboarding'
    | '/rh/organograma'
    | '/rh/pdi'
    | '/rh/producao'
    | '/rh/reconhecimentos'
    | '/rh/recrutamento'
    | '/rh/treinamentos'
    | '/rh/turnover'
    | '/prospeccao'
    | '/radar'
    | '/rh'
    | '/prospeccao/admin/leads'
    | '/rh/colaboradores/$id'
    | '/rh/portal/$kpi'
    | '/api/public/hooks/competicao-fechar'
    | '/api/public/hooks/followup-lembretes'
    | '/api/public/hooks/radar-diario'
    | '/api/public/hooks/radar-diario-worker'
    | '/api/public/hooks/radar-distribuir'
    | '/api/public/hooks/radar-semanal'
    | '/api/public/hooks/tomadores-repor'
    | '/api/public/whatsapp/webhook'
    | '/rh/portal'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/alagoas'
    | '/_authenticated/calculadora-al'
    | '/_authenticated/contrato'
    | '/_authenticated/pesquisas'
    | '/_authenticated/qrcodes'
    | '/_authenticated/radar'
    | '/_authenticated/rh'
    | '/_authenticated/servidores-sem-acesso'
    | '/_authenticated/simulacao-alagoas'
    | '/_authenticated/tomadores-al'
    | '/_authenticated/whatsapp'
    | '/aprovacao/$token'
    | '/consultora/$token'
    | '/_authenticated/pos-venda/avaliacoes'
    | '/_authenticated/producao/competicao'
    | '/_authenticated/producao/metas'
    | '/_authenticated/producao/meu-dia'
    | '/_authenticated/producao/ranking'
    | '/_authenticated/prospeccao/$leadId'
    | '/_authenticated/prospeccao/admin'
    | '/_authenticated/prospeccao/followups'
    | '/_authenticated/prospeccao/promovidos'
    | '/_authenticated/prospeccao/promovidos-recentemente'
    | '/_authenticated/prospeccao/promovidos-recentes'
    | '/_authenticated/prospeccao/qualidade'
    | '/_authenticated/prospeccao/recentes'
    | '/_authenticated/radar/arquivos'
    | '/_authenticated/radar/busca-diaria'
    | '/_authenticated/radar/importar'
    | '/_authenticated/radar/registros'
    | '/_authenticated/rh/acessos'
    | '/_authenticated/rh/avaliacoes'
    | '/_authenticated/rh/banco-horas'
    | '/_authenticated/rh/cargos'
    | '/_authenticated/rh/clima'
    | '/_authenticated/rh/colaboradores'
    | '/_authenticated/rh/dashboard'
    | '/_authenticated/rh/departamentos'
    | '/_authenticated/rh/desligamentos'
    | '/_authenticated/rh/documentos'
    | '/_authenticated/rh/equipamentos'
    | '/_authenticated/rh/ferias'
    | '/_authenticated/rh/holerites'
    | '/_authenticated/rh/ocorrencias'
    | '/_authenticated/rh/okrs'
    | '/_authenticated/rh/onboarding'
    | '/_authenticated/rh/organograma'
    | '/_authenticated/rh/pdi'
    | '/_authenticated/rh/portal'
    | '/_authenticated/rh/producao'
    | '/_authenticated/rh/reconhecimentos'
    | '/_authenticated/rh/recrutamento'
    | '/_authenticated/rh/treinamentos'
    | '/_authenticated/rh/turnover'
    | '/_authenticated/prospeccao/'
    | '/_authenticated/radar/'
    | '/_authenticated/rh/'
    | '/_authenticated/prospeccao/admin/leads'
    | '/_authenticated/rh/colaboradores/$id'
    | '/_authenticated/rh/portal/$kpi'
    | '/api/public/hooks/competicao-fechar'
    | '/api/public/hooks/followup-lembretes'
    | '/api/public/hooks/radar-diario'
    | '/api/public/hooks/radar-diario-worker'
    | '/api/public/hooks/radar-distribuir'
    | '/api/public/hooks/radar-semanal'
    | '/api/public/hooks/tomadores-repor'
    | '/api/public/whatsapp/webhook'
    | '/_authenticated/rh/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AprovacaoTokenRoute: typeof AprovacaoTokenRoute
  ConsultoraTokenRoute: typeof ConsultoraTokenRoute
  ApiPublicHooksCompeticaoFecharRoute: typeof ApiPublicHooksCompeticaoFecharRoute
  ApiPublicHooksFollowupLembretesRoute: typeof ApiPublicHooksFollowupLembretesRoute
  ApiPublicHooksRadarDiarioRoute: typeof ApiPublicHooksRadarDiarioRoute
  ApiPublicHooksRadarDiarioWorkerRoute: typeof ApiPublicHooksRadarDiarioWorkerRoute
  ApiPublicHooksRadarDistribuirRoute: typeof ApiPublicHooksRadarDistribuirRoute
  ApiPublicHooksRadarSemanalRoute: typeof ApiPublicHooksRadarSemanalRoute
  ApiPublicHooksTomadoresReporRoute: typeof ApiPublicHooksTomadoresReporRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/alagoas': {
      id: '/_authenticated/alagoas'
      path: '/alagoas'
      fullPath: '/alagoas'
      preLoaderRoute: typeof AuthenticatedAlagoasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calculadora-al': {
      id: '/_authenticated/calculadora-al'
      path: '/calculadora-al'
      fullPath: '/calculadora-al'
      preLoaderRoute: typeof AuthenticatedCalculadoraAlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contrato': {
      id: '/_authenticated/contrato'
      path: '/contrato'
      fullPath: '/contrato'
      preLoaderRoute: typeof AuthenticatedContratoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pesquisas': {
      id: '/_authenticated/pesquisas'
      path: '/pesquisas'
      fullPath: '/pesquisas'
      preLoaderRoute: typeof AuthenticatedPesquisasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qrcodes': {
      id: '/_authenticated/qrcodes'
      path: '/qrcodes'
      fullPath: '/qrcodes'
      preLoaderRoute: typeof AuthenticatedQrcodesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/radar': {
      id: '/_authenticated/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof AuthenticatedRadarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rh': {
      id: '/_authenticated/rh'
      path: '/rh'
      fullPath: '/rh'
      preLoaderRoute: typeof AuthenticatedRhRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/servidores-sem-acesso': {
      id: '/_authenticated/servidores-sem-acesso'
      path: '/servidores-sem-acesso'
      fullPath: '/servidores-sem-acesso'
      preLoaderRoute: typeof AuthenticatedServidoresSemAcessoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/simulacao-alagoas': {
      id: '/_authenticated/simulacao-alagoas'
      path: '/simulacao-alagoas'
      fullPath: '/simulacao-alagoas'
      preLoaderRoute: typeof AuthenticatedSimulacaoAlagoasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tomadores-al': {
      id: '/_authenticated/tomadores-al'
      path: '/tomadores-al'
      fullPath: '/tomadores-al'
      preLoaderRoute: typeof AuthenticatedTomadoresAlRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/aprovacao/$token': {
      id: '/aprovacao/$token'
      path: '/aprovacao/$token'
      fullPath: '/aprovacao/$token'
      preLoaderRoute: typeof AprovacaoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultora/$token': {
      id: '/consultora/$token'
      path: '/consultora/$token'
      fullPath: '/consultora/$token'
      preLoaderRoute: typeof ConsultoraTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pos-venda/avaliacoes': {
      id: '/_authenticated/pos-venda/avaliacoes'
      path: '/pos-venda/avaliacoes'
      fullPath: '/pos-venda/avaliacoes'
      preLoaderRoute: typeof AuthenticatedPosVendaAvaliacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/producao/competicao': {
      id: '/_authenticated/producao/competicao'
      path: '/producao/competicao'
      fullPath: '/producao/competicao'
      preLoaderRoute: typeof AuthenticatedProducaoCompeticaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/producao/metas': {
      id: '/_authenticated/producao/metas'
      path: '/producao/metas'
      fullPath: '/producao/metas'
      preLoaderRoute: typeof AuthenticatedProducaoMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/producao/meu-dia': {
      id: '/_authenticated/producao/meu-dia'
      path: '/producao/meu-dia'
      fullPath: '/producao/meu-dia'
      preLoaderRoute: typeof AuthenticatedProducaoMeuDiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/producao/ranking': {
      id: '/_authenticated/producao/ranking'
      path: '/producao/ranking'
      fullPath: '/producao/ranking'
      preLoaderRoute: typeof AuthenticatedProducaoRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prospeccao/': {
      id: '/_authenticated/prospeccao/'
      path: '/prospeccao'
      fullPath: '/prospeccao/'
      preLoaderRoute: typeof AuthenticatedProspeccaoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prospeccao/$leadId': {
      id: '/_authenticated/prospeccao/$leadId'
      path: '/prospeccao/$leadId'
      fullPath: '/prospeccao/$leadId'
      preLoaderRoute: typeof AuthenticatedProspeccaoLeadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prospeccao/admin': {
      id: '/_authenticated/prospeccao/admin'
      path: '/prospeccao/admin'
      fullPath: '/prospeccao/admin'
      preLoaderRoute: typeof AuthenticatedProspeccaoAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prospeccao/followups': {
      id: '/_authenticated/prospeccao/followups'
      path: '/prospeccao/followups'
      fullPath: '/prospeccao/followups'
      preLoaderRoute: typeof AuthenticatedProspeccaoFollowupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prospeccao/promovidos': {
      id: '/_authenticated/prospeccao/promovidos'
      path: '/prospeccao/promovidos'
      fullPath: '/prospeccao/promovidos'
      preLoaderRoute: typeof AuthenticatedProspeccaoPromovidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prospeccao/promovidos-recentemente': {
      id: '/_authenticated/prospeccao/promovidos-recentemente'
      path: '/prospeccao/promovidos-recentemente'
      fullPath: '/prospeccao/promovidos-recentemente'
      preLoaderRoute: typeof AuthenticatedProspeccaoPromovidosRecentementeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prospeccao/promovidos-recentes': {
      id: '/_authenticated/prospeccao/promovidos-recentes'
      path: '/prospeccao/promovidos-recentes'
      fullPath: '/prospeccao/promovidos-recentes'
      preLoaderRoute: typeof AuthenticatedProspeccaoPromovidosRecentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prospeccao/qualidade': {
      id: '/_authenticated/prospeccao/qualidade'
      path: '/prospeccao/qualidade'
      fullPath: '/prospeccao/qualidade'
      preLoaderRoute: typeof AuthenticatedProspeccaoQualidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prospeccao/recentes': {
      id: '/_authenticated/prospeccao/recentes'
      path: '/prospeccao/recentes'
      fullPath: '/prospeccao/recentes'
      preLoaderRoute: typeof AuthenticatedProspeccaoRecentesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/radar/': {
      id: '/_authenticated/radar/'
      path: '/'
      fullPath: '/radar/'
      preLoaderRoute: typeof AuthenticatedRadarIndexRouteImport
      parentRoute: typeof AuthenticatedRadarRoute
    }
    '/_authenticated/radar/arquivos': {
      id: '/_authenticated/radar/arquivos'
      path: '/arquivos'
      fullPath: '/radar/arquivos'
      preLoaderRoute: typeof AuthenticatedRadarArquivosRouteImport
      parentRoute: typeof AuthenticatedRadarRoute
    }
    '/_authenticated/radar/busca-diaria': {
      id: '/_authenticated/radar/busca-diaria'
      path: '/busca-diaria'
      fullPath: '/radar/busca-diaria'
      preLoaderRoute: typeof AuthenticatedRadarBuscaDiariaRouteImport
      parentRoute: typeof AuthenticatedRadarRoute
    }
    '/_authenticated/radar/importar': {
      id: '/_authenticated/radar/importar'
      path: '/importar'
      fullPath: '/radar/importar'
      preLoaderRoute: typeof AuthenticatedRadarImportarRouteImport
      parentRoute: typeof AuthenticatedRadarRoute
    }
    '/_authenticated/radar/registros': {
      id: '/_authenticated/radar/registros'
      path: '/registros'
      fullPath: '/radar/registros'
      preLoaderRoute: typeof AuthenticatedRadarRegistrosRouteImport
      parentRoute: typeof AuthenticatedRadarRoute
    }
    '/_authenticated/rh/': {
      id: '/_authenticated/rh/'
      path: '/'
      fullPath: '/rh/'
      preLoaderRoute: typeof AuthenticatedRhIndexRouteImport
      parentRoute: typeof AuthenticatedRhRoute
    }
    '/_authenticated/rh/acessos': {
      id: '/_authenticated/rh/acessos'
      path: '/acessos'
      fullPath: '/rh/acessos'
      preLoaderRoute: typeof AuthenticatedRhAcessosRouteImport
      parentRoute: typeof AuthenticatedRhRoute
    }
    '/_authenticated/rh/avaliacoes': {
      id: '/_authenticated/rh/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/rh/avaliacoes'
      preLoaderRoute: typeof AuthenticatedRhAvaliacoesRouteImport
      parentRoute: typeof AuthenticatedRhRoute
    }
    '/_authenticated/rh/banco-horas': {
      id: '/_authenticated/rh/banco-horas'
      path: '/banco-horas'
      fullPath: '/rh/banco-horas'
      preLoaderRoute: typeof AuthenticatedRhBancoHorasRouteImport
      parentRoute: typeof AuthenticatedRhRoute
    }
    '/_authenticated/rh/cargos': {
      id: '/_authenticated/rh/cargos'
      path: '/cargos'
      fullPath: '/rh/cargos'
      preLoaderRoute: typeof AuthenticatedRhCargosRouteImport
      parentRoute: typeof AuthenticatedRhRoute
    }
    '/_authenticated/rh/clima': {
      id: '/_authenticated/rh/clima'
      path: '/clima'
      fullPath: '/rh/clima'
      preLoaderRoute: typeof AuthenticatedRhClimaRouteImport
      parentRoute: typeof AuthenticatedRhRoute
    }
    '/_authenticated/rh/colaboradores': {
      id: '/_authenticated/rh/colaboradores'
      path: '/colaboradores'
      fullPath: '/rh/colaboradores'
      preLoaderRoute: typeof AuthenticatedRhColaboradoresRouteImport
      parentRoute: typeof AuthenticatedRhRoute
    }
    '/_authenticated/rh/dashboard': {
      id: '/_authenticated/rh/dashboard'
      path: '/dashboard'
      fullPath: '/rh/dashboard'
      preLoaderRoute: typeof AuthenticatedRhDashboardRouteImport
      parentRoute: typeof AuthenticatedRhRoute
    }
    '/_authenticated/rh/departamentos': {
      id: '/_authenticated/rh/departamentos'
      path: '/departamentos'
      fullPath: '/rh/departamentos'
      preLoaderRoute: typeof AuthenticatedRhDepartamentosRouteImport
      parentRoute: typeof AuthenticatedRhRoute
    }
    '/_authenticated/rh/desligamentos': {
      id: '/_authenticated/rh/desligamentos'
      path: '/desligamentos'
      fullPath: '/rh/desligamentos'
      preLoaderRoute: typeof AuthenticatedRhDesligamentosRouteImport
      parentRoute: typeof AuthenticatedRhRoute
    }
    '/_authenticated/rh/documentos': {
      id: '/_authenticated/rh/documentos'
      path: '/documentos'
      fullPath: '/rh/documentos'
      preLoaderRoute: typeof AuthenticatedRhDocumentosRouteImport
      parentRoute: typeof AuthenticatedRhRoute
    }
    '/_authenticated/rh/equipamentos': {
      id: '/_authenticated/rh/equipamentos'
      path: '/equipamentos'
      fullPath: '/rh/equipamentos'
      preLoaderRoute: typeof AuthenticatedRhEquipamentosRouteImport
      parentRoute: typeof AuthenticatedRhRoute
    }
    '/_authenticated/rh/ferias': {
      id: '/_authenticated/rh/ferias'
      path: '/ferias'
      fullPath: '/rh/ferias'
      preLoaderRoute: typeof AuthenticatedRhFeriasRouteImport
      parentRoute: typeof AuthenticatedRhRoute
    }
    '/_authenticated/rh/holerites': {
      id: '/_authenticated/rh/holerites'
      path: '/holerites'
      fullPath: '/rh/holerites'
      preLoaderRoute: typeof AuthenticatedRhHoleritesRouteImport
      parentRoute: typeof AuthenticatedRhRoute
    }
    '/_authenticated/rh/ocorrencias': {
      id: '/_authenticated/rh/ocorrencias'
      path: '/ocorrencias'
      fullPath: '/rh/ocorrencias'
      preLoaderRoute: typeof AuthenticatedRhOcorrenciasRouteImport
      parentRoute: typeof AuthenticatedRhRoute
    }
    '/_authenticated/rh/okrs': {
      id: '/_authenticated/rh/okrs'
      path: '/okrs'
      fullPath: '/rh/okrs'
      preLoaderRoute: typeof AuthenticatedRhOkrsRouteImport
      parentRoute: typeof AuthenticatedRhRoute
    }
    '/_authenticated/rh/onboarding': {
      id: '/_authenticated/rh/onboarding'
      path: '/onboarding'
      fullPath: '/rh/onboarding'
      preLoaderRoute: typeof AuthenticatedRhOnboardingRouteImport
      parentRoute: typeof AuthenticatedRhRoute
    }
    '/_authenticated/rh/organograma': {
      id: '/_authenticated/rh/organograma'
      path: '/organograma'
      fullPath: '/rh/organograma'
      preLoaderRoute: typeof AuthenticatedRhOrganogramaRouteImport
      parentRoute: typeof AuthenticatedRhRoute
    }
    '/_authenticated/rh/pdi': {
      id: '/_authenticated/rh/pdi'
      path: '/pdi'
      fullPath: '/rh/pdi'
      preLoaderRoute: typeof AuthenticatedRhPdiRouteImport
      parentRoute: typeof AuthenticatedRhRoute
    }
    '/_authenticated/rh/portal': {
      id: '/_authenticated/rh/portal'
      path: '/portal'
      fullPath: '/rh/portal'
      preLoaderRoute: typeof AuthenticatedRhPortalRouteImport
      parentRoute: typeof AuthenticatedRhRoute
    }
    '/_authenticated/rh/producao': {
      id: '/_authenticated/rh/producao'
      path: '/producao'
      fullPath: '/rh/producao'
      preLoaderRoute: typeof AuthenticatedRhProducaoRouteImport
      parentRoute: typeof AuthenticatedRhRoute
    }
    '/_authenticated/rh/reconhecimentos': {
      id: '/_authenticated/rh/reconhecimentos'
      path: '/reconhecimentos'
      fullPath: '/rh/reconhecimentos'
      preLoaderRoute: typeof AuthenticatedRhReconhecimentosRouteImport
      parentRoute: typeof AuthenticatedRhRoute
    }
    '/_authenticated/rh/recrutamento': {
      id: '/_authenticated/rh/recrutamento'
      path: '/recrutamento'
      fullPath: '/rh/recrutamento'
      preLoaderRoute: typeof AuthenticatedRhRecrutamentoRouteImport
      parentRoute: typeof AuthenticatedRhRoute
    }
    '/_authenticated/rh/treinamentos': {
      id: '/_authenticated/rh/treinamentos'
      path: '/treinamentos'
      fullPath: '/rh/treinamentos'
      preLoaderRoute: typeof AuthenticatedRhTreinamentosRouteImport
      parentRoute: typeof AuthenticatedRhRoute
    }
    '/_authenticated/rh/turnover': {
      id: '/_authenticated/rh/turnover'
      path: '/turnover'
      fullPath: '/rh/turnover'
      preLoaderRoute: typeof AuthenticatedRhTurnoverRouteImport
      parentRoute: typeof AuthenticatedRhRoute
    }
    '/_authenticated/prospeccao/admin/leads': {
      id: '/_authenticated/prospeccao/admin/leads'
      path: '/leads'
      fullPath: '/prospeccao/admin/leads'
      preLoaderRoute: typeof AuthenticatedProspeccaoAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedProspeccaoAdminRoute
    }
    '/_authenticated/rh/colaboradores/$id': {
      id: '/_authenticated/rh/colaboradores/$id'
      path: '/$id'
      fullPath: '/rh/colaboradores/$id'
      preLoaderRoute: typeof AuthenticatedRhColaboradoresIdRouteImport
      parentRoute: typeof AuthenticatedRhColaboradoresRoute
    }
    '/_authenticated/rh/portal/': {
      id: '/_authenticated/rh/portal/'
      path: '/'
      fullPath: '/rh/portal/'
      preLoaderRoute: typeof AuthenticatedRhPortalIndexRouteImport
      parentRoute: typeof AuthenticatedRhPortalRoute
    }
    '/_authenticated/rh/portal/$kpi': {
      id: '/_authenticated/rh/portal/$kpi'
      path: '/$kpi'
      fullPath: '/rh/portal/$kpi'
      preLoaderRoute: typeof AuthenticatedRhPortalKpiRouteImport
      parentRoute: typeof AuthenticatedRhPortalRoute
    }
    '/api/public/hooks/competicao-fechar': {
      id: '/api/public/hooks/competicao-fechar'
      path: '/api/public/hooks/competicao-fechar'
      fullPath: '/api/public/hooks/competicao-fechar'
      preLoaderRoute: typeof ApiPublicHooksCompeticaoFecharRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/followup-lembretes': {
      id: '/api/public/hooks/followup-lembretes'
      path: '/api/public/hooks/followup-lembretes'
      fullPath: '/api/public/hooks/followup-lembretes'
      preLoaderRoute: typeof ApiPublicHooksFollowupLembretesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/radar-diario': {
      id: '/api/public/hooks/radar-diario'
      path: '/api/public/hooks/radar-diario'
      fullPath: '/api/public/hooks/radar-diario'
      preLoaderRoute: typeof ApiPublicHooksRadarDiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/radar-diario-worker': {
      id: '/api/public/hooks/radar-diario-worker'
      path: '/api/public/hooks/radar-diario-worker'
      fullPath: '/api/public/hooks/radar-diario-worker'
      preLoaderRoute: typeof ApiPublicHooksRadarDiarioWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/radar-distribuir': {
      id: '/api/public/hooks/radar-distribuir'
      path: '/api/public/hooks/radar-distribuir'
      fullPath: '/api/public/hooks/radar-distribuir'
      preLoaderRoute: typeof ApiPublicHooksRadarDistribuirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/radar-semanal': {
      id: '/api/public/hooks/radar-semanal'
      path: '/api/public/hooks/radar-semanal'
      fullPath: '/api/public/hooks/radar-semanal'
      preLoaderRoute: typeof ApiPublicHooksRadarSemanalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/tomadores-repor': {
      id: '/api/public/hooks/tomadores-repor'
      path: '/api/public/hooks/tomadores-repor'
      fullPath: '/api/public/hooks/tomadores-repor'
      preLoaderRoute: typeof ApiPublicHooksTomadoresReporRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRadarRouteChildren {
  AuthenticatedRadarArquivosRoute: typeof AuthenticatedRadarArquivosRoute
  AuthenticatedRadarBuscaDiariaRoute: typeof AuthenticatedRadarBuscaDiariaRoute
  AuthenticatedRadarImportarRoute: typeof AuthenticatedRadarImportarRoute
  AuthenticatedRadarRegistrosRoute: typeof AuthenticatedRadarRegistrosRoute
  AuthenticatedRadarIndexRoute: typeof AuthenticatedRadarIndexRoute
}

const AuthenticatedRadarRouteChildren: AuthenticatedRadarRouteChildren = {
  AuthenticatedRadarArquivosRoute: AuthenticatedRadarArquivosRoute,
  AuthenticatedRadarBuscaDiariaRoute: AuthenticatedRadarBuscaDiariaRoute,
  AuthenticatedRadarImportarRoute: AuthenticatedRadarImportarRoute,
  AuthenticatedRadarRegistrosRoute: AuthenticatedRadarRegistrosRoute,
  AuthenticatedRadarIndexRoute: AuthenticatedRadarIndexRoute,
}

const AuthenticatedRadarRouteWithChildren =
  AuthenticatedRadarRoute._addFileChildren(AuthenticatedRadarRouteChildren)

interface AuthenticatedRhColaboradoresRouteChildren {
  AuthenticatedRhColaboradoresIdRoute: typeof AuthenticatedRhColaboradoresIdRoute
}

const AuthenticatedRhColaboradoresRouteChildren: AuthenticatedRhColaboradoresRouteChildren =
  {
    AuthenticatedRhColaboradoresIdRoute: AuthenticatedRhColaboradoresIdRoute,
  }

const AuthenticatedRhColaboradoresRouteWithChildren =
  AuthenticatedRhColaboradoresRoute._addFileChildren(
    AuthenticatedRhColaboradoresRouteChildren,
  )

interface AuthenticatedRhPortalRouteChildren {
  AuthenticatedRhPortalKpiRoute: typeof AuthenticatedRhPortalKpiRoute
  AuthenticatedRhPortalIndexRoute: typeof AuthenticatedRhPortalIndexRoute
}

const AuthenticatedRhPortalRouteChildren: AuthenticatedRhPortalRouteChildren = {
  AuthenticatedRhPortalKpiRoute: AuthenticatedRhPortalKpiRoute,
  AuthenticatedRhPortalIndexRoute: AuthenticatedRhPortalIndexRoute,
}

const AuthenticatedRhPortalRouteWithChildren =
  AuthenticatedRhPortalRoute._addFileChildren(
    AuthenticatedRhPortalRouteChildren,
  )

interface AuthenticatedRhRouteChildren {
  AuthenticatedRhAcessosRoute: typeof AuthenticatedRhAcessosRoute
  AuthenticatedRhAvaliacoesRoute: typeof AuthenticatedRhAvaliacoesRoute
  AuthenticatedRhBancoHorasRoute: typeof AuthenticatedRhBancoHorasRoute
  AuthenticatedRhCargosRoute: typeof AuthenticatedRhCargosRoute
  AuthenticatedRhClimaRoute: typeof AuthenticatedRhClimaRoute
  AuthenticatedRhColaboradoresRoute: typeof AuthenticatedRhColaboradoresRouteWithChildren
  AuthenticatedRhDashboardRoute: typeof AuthenticatedRhDashboardRoute
  AuthenticatedRhDepartamentosRoute: typeof AuthenticatedRhDepartamentosRoute
  AuthenticatedRhDesligamentosRoute: typeof AuthenticatedRhDesligamentosRoute
  AuthenticatedRhDocumentosRoute: typeof AuthenticatedRhDocumentosRoute
  AuthenticatedRhEquipamentosRoute: typeof AuthenticatedRhEquipamentosRoute
  AuthenticatedRhFeriasRoute: typeof AuthenticatedRhFeriasRoute
  AuthenticatedRhHoleritesRoute: typeof AuthenticatedRhHoleritesRoute
  AuthenticatedRhOcorrenciasRoute: typeof AuthenticatedRhOcorrenciasRoute
  AuthenticatedRhOkrsRoute: typeof AuthenticatedRhOkrsRoute
  AuthenticatedRhOnboardingRoute: typeof AuthenticatedRhOnboardingRoute
  AuthenticatedRhOrganogramaRoute: typeof AuthenticatedRhOrganogramaRoute
  AuthenticatedRhPdiRoute: typeof AuthenticatedRhPdiRoute
  AuthenticatedRhPortalRoute: typeof AuthenticatedRhPortalRouteWithChildren
  AuthenticatedRhProducaoRoute: typeof AuthenticatedRhProducaoRoute
  AuthenticatedRhReconhecimentosRoute: typeof AuthenticatedRhReconhecimentosRoute
  AuthenticatedRhRecrutamentoRoute: typeof AuthenticatedRhRecrutamentoRoute
  AuthenticatedRhTreinamentosRoute: typeof AuthenticatedRhTreinamentosRoute
  AuthenticatedRhTurnoverRoute: typeof AuthenticatedRhTurnoverRoute
  AuthenticatedRhIndexRoute: typeof AuthenticatedRhIndexRoute
}

const AuthenticatedRhRouteChildren: AuthenticatedRhRouteChildren = {
  AuthenticatedRhAcessosRoute: AuthenticatedRhAcessosRoute,
  AuthenticatedRhAvaliacoesRoute: AuthenticatedRhAvaliacoesRoute,
  AuthenticatedRhBancoHorasRoute: AuthenticatedRhBancoHorasRoute,
  AuthenticatedRhCargosRoute: AuthenticatedRhCargosRoute,
  AuthenticatedRhClimaRoute: AuthenticatedRhClimaRoute,
  AuthenticatedRhColaboradoresRoute:
    AuthenticatedRhColaboradoresRouteWithChildren,
  AuthenticatedRhDashboardRoute: AuthenticatedRhDashboardRoute,
  AuthenticatedRhDepartamentosRoute: AuthenticatedRhDepartamentosRoute,
  AuthenticatedRhDesligamentosRoute: AuthenticatedRhDesligamentosRoute,
  AuthenticatedRhDocumentosRoute: AuthenticatedRhDocumentosRoute,
  AuthenticatedRhEquipamentosRoute: AuthenticatedRhEquipamentosRoute,
  AuthenticatedRhFeriasRoute: AuthenticatedRhFeriasRoute,
  AuthenticatedRhHoleritesRoute: AuthenticatedRhHoleritesRoute,
  AuthenticatedRhOcorrenciasRoute: AuthenticatedRhOcorrenciasRoute,
  AuthenticatedRhOkrsRoute: AuthenticatedRhOkrsRoute,
  AuthenticatedRhOnboardingRoute: AuthenticatedRhOnboardingRoute,
  AuthenticatedRhOrganogramaRoute: AuthenticatedRhOrganogramaRoute,
  AuthenticatedRhPdiRoute: AuthenticatedRhPdiRoute,
  AuthenticatedRhPortalRoute: AuthenticatedRhPortalRouteWithChildren,
  AuthenticatedRhProducaoRoute: AuthenticatedRhProducaoRoute,
  AuthenticatedRhReconhecimentosRoute: AuthenticatedRhReconhecimentosRoute,
  AuthenticatedRhRecrutamentoRoute: AuthenticatedRhRecrutamentoRoute,
  AuthenticatedRhTreinamentosRoute: AuthenticatedRhTreinamentosRoute,
  AuthenticatedRhTurnoverRoute: AuthenticatedRhTurnoverRoute,
  AuthenticatedRhIndexRoute: AuthenticatedRhIndexRoute,
}

const AuthenticatedRhRouteWithChildren = AuthenticatedRhRoute._addFileChildren(
  AuthenticatedRhRouteChildren,
)

interface AuthenticatedProspeccaoAdminRouteChildren {
  AuthenticatedProspeccaoAdminLeadsRoute: typeof AuthenticatedProspeccaoAdminLeadsRoute
}

const AuthenticatedProspeccaoAdminRouteChildren: AuthenticatedProspeccaoAdminRouteChildren =
  {
    AuthenticatedProspeccaoAdminLeadsRoute:
      AuthenticatedProspeccaoAdminLeadsRoute,
  }

const AuthenticatedProspeccaoAdminRouteWithChildren =
  AuthenticatedProspeccaoAdminRoute._addFileChildren(
    AuthenticatedProspeccaoAdminRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlagoasRoute: typeof AuthenticatedAlagoasRoute
  AuthenticatedCalculadoraAlRoute: typeof AuthenticatedCalculadoraAlRoute
  AuthenticatedContratoRoute: typeof AuthenticatedContratoRoute
  AuthenticatedPesquisasRoute: typeof AuthenticatedPesquisasRoute
  AuthenticatedQrcodesRoute: typeof AuthenticatedQrcodesRoute
  AuthenticatedRadarRoute: typeof AuthenticatedRadarRouteWithChildren
  AuthenticatedRhRoute: typeof AuthenticatedRhRouteWithChildren
  AuthenticatedServidoresSemAcessoRoute: typeof AuthenticatedServidoresSemAcessoRoute
  AuthenticatedSimulacaoAlagoasRoute: typeof AuthenticatedSimulacaoAlagoasRoute
  AuthenticatedTomadoresAlRoute: typeof AuthenticatedTomadoresAlRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
  AuthenticatedPosVendaAvaliacoesRoute: typeof AuthenticatedPosVendaAvaliacoesRoute
  AuthenticatedProducaoCompeticaoRoute: typeof AuthenticatedProducaoCompeticaoRoute
  AuthenticatedProducaoMetasRoute: typeof AuthenticatedProducaoMetasRoute
  AuthenticatedProducaoMeuDiaRoute: typeof AuthenticatedProducaoMeuDiaRoute
  AuthenticatedProducaoRankingRoute: typeof AuthenticatedProducaoRankingRoute
  AuthenticatedProspeccaoLeadIdRoute: typeof AuthenticatedProspeccaoLeadIdRoute
  AuthenticatedProspeccaoAdminRoute: typeof AuthenticatedProspeccaoAdminRouteWithChildren
  AuthenticatedProspeccaoFollowupsRoute: typeof AuthenticatedProspeccaoFollowupsRoute
  AuthenticatedProspeccaoPromovidosRoute: typeof AuthenticatedProspeccaoPromovidosRoute
  AuthenticatedProspeccaoPromovidosRecentementeRoute: typeof AuthenticatedProspeccaoPromovidosRecentementeRoute
  AuthenticatedProspeccaoPromovidosRecentesRoute: typeof AuthenticatedProspeccaoPromovidosRecentesRoute
  AuthenticatedProspeccaoQualidadeRoute: typeof AuthenticatedProspeccaoQualidadeRoute
  AuthenticatedProspeccaoRecentesRoute: typeof AuthenticatedProspeccaoRecentesRoute
  AuthenticatedProspeccaoIndexRoute: typeof AuthenticatedProspeccaoIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlagoasRoute: AuthenticatedAlagoasRoute,
  AuthenticatedCalculadoraAlRoute: AuthenticatedCalculadoraAlRoute,
  AuthenticatedContratoRoute: AuthenticatedContratoRoute,
  AuthenticatedPesquisasRoute: AuthenticatedPesquisasRoute,
  AuthenticatedQrcodesRoute: AuthenticatedQrcodesRoute,
  AuthenticatedRadarRoute: AuthenticatedRadarRouteWithChildren,
  AuthenticatedRhRoute: AuthenticatedRhRouteWithChildren,
  AuthenticatedServidoresSemAcessoRoute: AuthenticatedServidoresSemAcessoRoute,
  AuthenticatedSimulacaoAlagoasRoute: AuthenticatedSimulacaoAlagoasRoute,
  AuthenticatedTomadoresAlRoute: AuthenticatedTomadoresAlRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
  AuthenticatedPosVendaAvaliacoesRoute: AuthenticatedPosVendaAvaliacoesRoute,
  AuthenticatedProducaoCompeticaoRoute: AuthenticatedProducaoCompeticaoRoute,
  AuthenticatedProducaoMetasRoute: AuthenticatedProducaoMetasRoute,
  AuthenticatedProducaoMeuDiaRoute: AuthenticatedProducaoMeuDiaRoute,
  AuthenticatedProducaoRankingRoute: AuthenticatedProducaoRankingRoute,
  AuthenticatedProspeccaoLeadIdRoute: AuthenticatedProspeccaoLeadIdRoute,
  AuthenticatedProspeccaoAdminRoute:
    AuthenticatedProspeccaoAdminRouteWithChildren,
  AuthenticatedProspeccaoFollowupsRoute: AuthenticatedProspeccaoFollowupsRoute,
  AuthenticatedProspeccaoPromovidosRoute:
    AuthenticatedProspeccaoPromovidosRoute,
  AuthenticatedProspeccaoPromovidosRecentementeRoute:
    AuthenticatedProspeccaoPromovidosRecentementeRoute,
  AuthenticatedProspeccaoPromovidosRecentesRoute:
    AuthenticatedProspeccaoPromovidosRecentesRoute,
  AuthenticatedProspeccaoQualidadeRoute: AuthenticatedProspeccaoQualidadeRoute,
  AuthenticatedProspeccaoRecentesRoute: AuthenticatedProspeccaoRecentesRoute,
  AuthenticatedProspeccaoIndexRoute: AuthenticatedProspeccaoIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AprovacaoTokenRoute: AprovacaoTokenRoute,
  ConsultoraTokenRoute: ConsultoraTokenRoute,
  ApiPublicHooksCompeticaoFecharRoute: ApiPublicHooksCompeticaoFecharRoute,
  ApiPublicHooksFollowupLembretesRoute: ApiPublicHooksFollowupLembretesRoute,
  ApiPublicHooksRadarDiarioRoute: ApiPublicHooksRadarDiarioRoute,
  ApiPublicHooksRadarDiarioWorkerRoute: ApiPublicHooksRadarDiarioWorkerRoute,
  ApiPublicHooksRadarDistribuirRoute: ApiPublicHooksRadarDistribuirRoute,
  ApiPublicHooksRadarSemanalRoute: ApiPublicHooksRadarSemanalRoute,
  ApiPublicHooksTomadoresReporRoute: ApiPublicHooksTomadoresReporRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
