/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServidoresSemAcessoRouteImport } from './routes/servidores-sem-acesso'
import { Route as SafeConsigRouteImport } from './routes/safe-consig'
import { Route as PesquisasRouteImport } from './routes/pesquisas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LimpezaRouteImport } from './routes/limpeza'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContratoRouteImport } from './routes/contrato'
import { Route as ConsultasRouteImport } from './routes/consultas'
import { Route as CalculadoraAlRouteImport } from './routes/calculadora-al'
import { Route as AlagoasRouteImport } from './routes/alagoas'
import { Route as IndexRouteImport } from './routes/index'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServidoresSemAcessoRoute = ServidoresSemAcessoRouteImport.update({
  id: '/servidores-sem-acesso',
  path: '/servidores-sem-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const SafeConsigRoute = SafeConsigRouteImport.update({
  id: '/safe-consig',
  path: '/safe-consig',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisasRoute = PesquisasRouteImport.update({
  id: '/pesquisas',
  path: '/pesquisas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LimpezaRoute = LimpezaRouteImport.update({
  id: '/limpeza',
  path: '/limpeza',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratoRoute = ContratoRouteImport.update({
  id: '/contrato',
  path: '/contrato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultasRoute = ConsultasRouteImport.update({
  id: '/consultas',
  path: '/consultas',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraAlRoute = CalculadoraAlRouteImport.update({
  id: '/calculadora-al',
  path: '/calculadora-al',
  getParentRoute: () => rootRouteImport,
} as any)
const AlagoasRoute = AlagoasRouteImport.update({
  id: '/alagoas',
  path: '/alagoas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alagoas': typeof AlagoasRoute
  '/calculadora-al': typeof CalculadoraAlRoute
  '/consultas': typeof ConsultasRoute
  '/contrato': typeof ContratoRoute
  '/dashboard': typeof DashboardRoute
  '/limpeza': typeof LimpezaRoute
  '/login': typeof LoginRoute
  '/pesquisas': typeof PesquisasRoute
  '/safe-consig': typeof SafeConsigRoute
  '/servidores-sem-acesso': typeof ServidoresSemAcessoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alagoas': typeof AlagoasRoute
  '/calculadora-al': typeof CalculadoraAlRoute
  '/consultas': typeof ConsultasRoute
  '/contrato': typeof ContratoRoute
  '/dashboard': typeof DashboardRoute
  '/limpeza': typeof LimpezaRoute
  '/login': typeof LoginRoute
  '/pesquisas': typeof PesquisasRoute
  '/safe-consig': typeof SafeConsigRoute
  '/servidores-sem-acesso': typeof ServidoresSemAcessoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/upload': typeof UploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alagoas': typeof AlagoasRoute
  '/calculadora-al': typeof CalculadoraAlRoute
  '/consultas': typeof ConsultasRoute
  '/contrato': typeof ContratoRoute
  '/dashboard': typeof DashboardRoute
  '/limpeza': typeof LimpezaRoute
  '/login': typeof LoginRoute
  '/pesquisas': typeof PesquisasRoute
  '/safe-consig': typeof SafeConsigRoute
  '/servidores-sem-acesso': typeof ServidoresSemAcessoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/upload': typeof UploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alagoas'
    | '/calculadora-al'
    | '/consultas'
    | '/contrato'
    | '/dashboard'
    | '/limpeza'
    | '/login'
    | '/pesquisas'
    | '/safe-consig'
    | '/servidores-sem-acesso'
    | '/sitemap.xml'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alagoas'
    | '/calculadora-al'
    | '/consultas'
    | '/contrato'
    | '/dashboard'
    | '/limpeza'
    | '/login'
    | '/pesquisas'
    | '/safe-consig'
    | '/servidores-sem-acesso'
    | '/sitemap.xml'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/alagoas'
    | '/calculadora-al'
    | '/consultas'
    | '/contrato'
    | '/dashboard'
    | '/limpeza'
    | '/login'
    | '/pesquisas'
    | '/safe-consig'
    | '/servidores-sem-acesso'
    | '/sitemap.xml'
    | '/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlagoasRoute: typeof AlagoasRoute
  CalculadoraAlRoute: typeof CalculadoraAlRoute
  ConsultasRoute: typeof ConsultasRoute
  ContratoRoute: typeof ContratoRoute
  DashboardRoute: typeof DashboardRoute
  LimpezaRoute: typeof LimpezaRoute
  LoginRoute: typeof LoginRoute
  PesquisasRoute: typeof PesquisasRoute
  SafeConsigRoute: typeof SafeConsigRoute
  ServidoresSemAcessoRoute: typeof ServidoresSemAcessoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UploadRoute: typeof UploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servidores-sem-acesso': {
      id: '/servidores-sem-acesso'
      path: '/servidores-sem-acesso'
      fullPath: '/servidores-sem-acesso'
      preLoaderRoute: typeof ServidoresSemAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safe-consig': {
      id: '/safe-consig'
      path: '/safe-consig'
      fullPath: '/safe-consig'
      preLoaderRoute: typeof SafeConsigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisas': {
      id: '/pesquisas'
      path: '/pesquisas'
      fullPath: '/pesquisas'
      preLoaderRoute: typeof PesquisasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limpeza': {
      id: '/limpeza'
      path: '/limpeza'
      fullPath: '/limpeza'
      preLoaderRoute: typeof LimpezaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contrato': {
      id: '/contrato'
      path: '/contrato'
      fullPath: '/contrato'
      preLoaderRoute: typeof ContratoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultas': {
      id: '/consultas'
      path: '/consultas'
      fullPath: '/consultas'
      preLoaderRoute: typeof ConsultasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora-al': {
      id: '/calculadora-al'
      path: '/calculadora-al'
      fullPath: '/calculadora-al'
      preLoaderRoute: typeof CalculadoraAlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alagoas': {
      id: '/alagoas'
      path: '/alagoas'
      fullPath: '/alagoas'
      preLoaderRoute: typeof AlagoasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlagoasRoute: AlagoasRoute,
  CalculadoraAlRoute: CalculadoraAlRoute,
  ConsultasRoute: ConsultasRoute,
  ContratoRoute: ContratoRoute,
  DashboardRoute: DashboardRoute,
  LimpezaRoute: LimpezaRoute,
  LoginRoute: LoginRoute,
  PesquisasRoute: PesquisasRoute,
  SafeConsigRoute: SafeConsigRoute,
  ServidoresSemAcessoRoute: ServidoresSemAcessoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UploadRoute: UploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
